; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Thu Aug 02 2018 20:00:35 GMT-0400 (EDT)
M561                ; clear any bed transform
G28                 ; home all axes
M98 Pdeployprobe.g  ; deploy mechanical Z probe
; Probe the bed at 4 points
G30 P0 X15 Y15 H0 Z-99999
G30 P1 X15 Y373 H0 Z-99999
G30 P2 X368 Y373 H0 Z-99999
G30 P3 X368 Y15 H0 Z-99999 S
M98 Pretractprobe.g ; retract mechanical Z probe
